### ISSUE TITLE
how to disable LSP warning, how to set LSP and how to uninstall specify LSP?

### ISSUE THREAD

**Issue by winimi** [jayli/vim-easycomplete#157] opened 2022-02-17 09:58 UTC

**Comment by jayli** [comment] 2022-02-17 11:06
use this config:

```vim
let g:easycomplete_diagnostics_enable = 0
let g:easycomplete_lsp_checking = 0
```

duplicate of #131

**Comment by winimi** [comment] 2022-02-18 02:28
> You have do it manuly.

OK, what should I set, show errors but no warning?

**Comment by jayli** [comment] 2022-02-18 03:45
```
rm -rf ~/.config/vim-easycomplete/servers/{$lsp-plugin-name}
```

**Closed** 2023-12-05 06:58 UTC
Labels: question
